### ISSUE TITLE
Allow "Browser" as screen type in manifest

### ISSUE THREAD

**Issue by boyofgreen** [pwa-builder/PWABuilder-CLI#275]
As in the AirB&B site:

https://www.airbnb.com/

**Comment by rnrneverdies** [comment]
Hi @boyofgreen, the site's manifest does not comply the w3c manifest schema since the valid value is "browser" (note lowercase). I think there is no elegant solution on our side taking into account how this validation is currently implemented. 
Perhaps fixing the manifest in the website would be the proper way to go.

Thoughts?

**Comment by marcoscaceres** [comment]
Let me know if I should ping someone at Airbnb. I know a few people there

**Comment by lencioni** [comment]
I'll fix it. Gotta go now, but should be in production tomorrowish.

**Comment by marcoscaceres** [comment]
Yay!!!! Thanks @lencioni! ⭐️

**Comment by boyofgreen** [comment]
Thanks @marcoscaceres and @lencioni  easiest fix ever!

**Comment by lencioni** [comment]
FYI this fix is heading to production for Airbnb right now.

**Comment by davrous** [comment]
Not an issue anymore on pwabuilder.com. Closing.
